### ISSUE TITLE
More information on project

### ISSUE THREAD

**Issue by zmr** [tibetdata/tibetdata.github.io#1]
Hi, I am creator of the Namsel OCR project (http://www.namsel.com/). Our group is highly interested in the collection and analysis of Tibetan data sources and were looking to possibly launch a similar data-sharing platform. Would love to be in contact with the creators of this site. --Zach

**Comment by tibetdata** [comment]
Hey, sorry for the late response Zach. Feel free to email me at tibetdata@gmail.com
